import '../styles/style.sass'

import type { AppProps } from 'next/app'
import React, { ReactDOM, RefObject, useEffect, useRef, useState } from 'react'

// import LocomotiveScroll from 'locomotive-scroll'
import { LocomotiveScrollProvider as RLSProvider } from 'react-locomotive-scroll'

import Head from 'next/head'
import Header from '../components/Header'
import Footer from '../components/Footer'
import useLocoScroll from '../components/functions/useLocoScroll'
import { BnovoLoadContextProvider } from '../components/bnovo/bnovoContext'
import { useRouter } from 'next/router'
import LoadingBar, { LoadingBarRef } from 'react-top-loading-bar'
import barba from '@barba/core';
import AppLayout from '@/components/AppLayout'



export default function App({ Component, pageProps }: AppProps) {
  const [width, setWidth] = useState<Number>(100)
  const [height, setHeight] = useState<Number>(100)
  const router = useRouter()
  // barba.init({
  //   views: [{
  //     namespace: 'home',
  //     beforeLeave(data) {
  //       // do something before leaving the current `index` namespace
  //     }
  //   }, {
  //     namespace: 'sauna',
  //     beforeEnter(data) {
  //       // do something before entering the `contact` namespace
  //     }
  //   }]
  // });

  const loaderRef = useRef<LoadingBarRef>(null)
  useEffect(() => {
    router.events.on('routeChangeStart', () => {
      loaderRef.current?.continuousStart()
    })

    router.events.on('routeChangeComplete', () => {
      loaderRef.current?.complete()
    })


  }, [pageProps])


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://widget.reservationsteps.ru/js/bnovo.js" async></script>

      </Head>

      <LoadingBar color='#262626' ref={loaderRef} height={2} />

      <BnovoLoadContextProvider>
        <AppLayout asPath={router.asPath}>
          <Component {...pageProps} />
        </AppLayout>
      </BnovoLoadContextProvider>
    </>
  )
}


