import 'swiper/css'
import 'swiper/css/bundle'
import "aos/dist/aos.css"
import '@mantine/core/styles.css'
import '@mantine/dates/styles.css'
import '@mantine/carousel/styles.css'
import '../styles/style.sass'

import type { AppProps } from 'next/app'
import React, { useContext, useEffect, useRef, useState } from 'react'

import Head from 'next/head'
import { BnovoContext, BnovoLoadContextProvider } from '../components/bnovo/bnovoContext'
import { useRouter } from 'next/router'
import LoadingBar, { LoadingBarRef } from 'react-top-loading-bar'
import AppLayout from '@/components/AppLayout'
import { YMProvider } from '@/components/ym/YMProvider'
import { createTheme, MantineProvider, rem } from '@mantine/core'
import ReactModal from 'react-modal'

const theme = createTheme({
  fontFamily: '"Roboto Serif", serif !important',
  fontSizes: {
    xxs: rem(12),
    xs: rem(15),
    sm: rem(18),
    md: rem(20),
    lg: rem(24),
    xl: rem(30),
  },
  lineHeights: {
    xs: '140%',
    sm: '140%',
    md: '140%',
    lg: '140%',
    xl: '140%',
  },
  colors: {

  },
  headings: {
    fontWeight: '400',
    fontFamily: '"Roboto Serif", serif',

    sizes: {
      h2: {
        fontWeight: '500',
        fontSize: rem(48),
        lineHeight: '140%',
      },
      h3: {
        fontWeight: '500',
        fontSize: rem(36),
        lineHeight: '140%',
      },
      h4: {
        fontWeight: '500',
        fontSize: rem(24),
        lineHeight: '140%',
      },
      h5: {
        fontWeight: '500',
        fontSize: rem(20),
        lineHeight: '140%',
      },
    },
  },
})


ReactModal.setAppElement('#__next')

export default function App({ Component, pageProps }: AppProps) {
  const router = useRouter()

  const loaderRef = useRef<LoadingBarRef>(null)
  useEffect(() => {
    router.events.on('routeChangeStart', () => {
      loaderRef.current?.continuousStart()
    })

    router.events.on('routeChangeComplete', () => {
      loaderRef.current?.complete()
    })


  }, [router.asPath])


  return (
    <>
      <Head>
        {/* <title>Create Next App</title> */}
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <LoadingBar color='#262626' ref={loaderRef} height={2} />

      <BnovoLoadContextProvider>
        <MantineProvider theme={theme}>
          <YMProvider counterId={94296197} options={{ trackLinks: true, clickmap: true, webVisor: true }}>
            <AppLayout asPath={router.asPath} pageProps={pageProps}>
              <Component {...pageProps} />
            </AppLayout>
          </YMProvider>
        </MantineProvider>
      </BnovoLoadContextProvider>
    </>
  )
}


